
version: '2'

services:

  web:
    image: somos/php
    environment:
      - XDEBUG=true
      - DNSDOCK_NAME=www
      - DNSDOCK_IMAGE=somos
    volumes:
      - ./:/var/www/html
    links:
      - db
      - cache:redis
    ports:
      - "8080:80"

  cache:
    image: redis

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=drupal
      - DNSDOCK_NAME=db
      - DNSDOCK_IMAGE=somos
    volumes:
      - mysql:/var/lib/mysql

  cli:
    image: somos/php-cli
    volumes:
      - ./:/app
      - ./setup.sh:/app/setup.sh
    entrypoint: [ "/app/setup.sh" ]

volumes:
  mysql:
